### ISSUE TITLE
不好意思，冒昧的问一下

### ISSUE THREAD

**Issue by skyfister** [abrahamgreyson/laravel-mns#2]
冒昧的问一下，exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'GuzzleHttp\Client' not found' in /vendor/abe/laravel-mns/lib/AliyunMNS/Http/HttpClient.php:32，我也没找到'GuzzleHttp\Client'这个类！是不是依赖包升级了呢？

**Comment by abrahamgreyson** [comment]
感谢反馈，可能是我本地已经安装了 Guzzle， 所以编写过程中忽略了这个依赖， 却没有报错。
我看了下， AliyunMNS SDK 本身需要 Guzzle 客户端。
你试着手动安装 https://github.com/guzzle/guzzle
一旦有时间，我会尽快修复。

**Comment by abrahamgreyson** [comment]
在你项目的根目录， `composer require guzzlehttp/guzzle` 会安装 Guzzle。

**Comment by skyfister** [comment]
好的，太给力了，Thanks！

**Comment by abrahamgreyson** [comment]
@skyfister 已经重新发版。

**Comment by skyfister** [comment]
好的
