### ISSUE TITLE
还有个问题想请教下

### ISSUE THREAD

**Issue by skyfister** [abrahamgreyson/laravel-mns#3]
abe/laravel-mns/src/Jobs/MnsJob这个类的release函数的$delay参数经过判断之后传给changeMessageVisibility函数的第二个参数还是为0，导致报错:visibilitytimeout必须在1到43200之间！

**Comment by abrahamgreyson** [comment]
方便发 PR 么？

**Comment by abrahamgreyson** [comment]
@skyfister 你好，感谢反馈，如果不方便发 pr， 能否帮助我重现错误？ 譬如 release 方法，当接收到什么样的参数， 会触发这个 bug？
