### ISSUE TITLE
你好 请教个问题

### ISSUE THREAD

**Issue by sj1370201** [abrahamgreyson/laravel-mns#4]
并且在你常用的 ServiceProvider 中注册队列驱动：这是啥意思啊？在哪添加啊

**Comment by abrahamgreyson** [comment]
这句话有什么说不清楚的地方吗？

**Comment by sj1370201** [comment]
是啊 不知道在哪加啊

**Comment by abrahamgreyson** [comment]
@sj1370201  在 app/Providers 下任意一个 Provider 中。
